project_id = "snkdhcilyorroeyeveul"

[functions.test-binance-connection]
verify_jwt = false

[functions.crypto-payment-webhook]
verify_jwt = false

[functions.notify-admins-alert-disabled]
verify_jwt = false
